import type { Application } from '@/types/application'
import { GUEST_USER_ID } from '@/lib/guest-session'

// 生成相对日期的辅助函数
function daysFromNow(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString().split('T')[0]
}

function daysAgo(days: number): string {
  return daysFromNow(-days)
}

export const DEMO_SEED_APPLICATIONS: Application[] = [
  // ========== 待投递 ==========
  {
    id: 'demo-001',
    user_id: GUEST_USER_ID,
    company_name: '腾讯',
    job_title: '前端开发工程师',
    stage: '待投递',
    next_deadline: daysFromNow(3),
    applied_at: null,
    result_status: 'ongoing',
    notes: '等内推码，学长说本周会发',
    jd_url: 'https://careers.tencent.com/...',
    jd_snapshot: '负责微信小程序框架开发，要求熟悉 Vue/React',
    resume_version: '前端-通用版',
    contact_info: '内推人：张学长 wx: zhangxxx',
    reminder_dismissed_at: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-002',
    user_id: GUEST_USER_ID,
    company_name: '小红书',
    job_title: '全栈开发实习',
    stage: '待投递',
    next_deadline: daysFromNow(5),
    applied_at: null,
    result_status: 'ongoing',
    notes: '需要准备作品集',
    jd_url: null,
    jd_snapshot: null,
    resume_version: null,
    contact_info: null,
    reminder_dismissed_at: null,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },

  // ========== 已投递 ==========
  {
    id: 'demo-003',
    user_id: GUEST_USER_ID,
    company_name: '美团',
    job_title: '后端开发工程师',
    stage: '已投递',
    next_deadline: null,
    applied_at: daysAgo(5),
    result_status: 'ongoing',
    notes: '官网投递，等简历筛选结果',
    jd_url: 'https://zhaopin.meituan.com/...',
    jd_snapshot: 'Java/Go 后端，负责外卖履约系统',
    resume_version: '后端-Java版',
    contact_info: null,
    reminder_dismissed_at: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-004',
    user_id: GUEST_USER_ID,
    company_name: '字节跳动',
    job_title: '前端开发实习生',
    stage: '已投递',
    next_deadline: null,
    applied_at: daysAgo(3),
    result_status: 'ongoing',
    notes: '投的抖音电商部门',
    jd_url: null,
    jd_snapshot: 'React + Node.js，有 SSR 经验优先',
    resume_version: '前端-通用版',
    contact_info: null,
    reminder_dismissed_at: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },

  // ========== 笔试 / OA ==========
  {
    id: 'demo-005',
    user_id: GUEST_USER_ID,
    company_name: '阿里巴巴',
    job_title: '前端开发工程师',
    stage: '笔试 / OA',
    next_deadline: daysFromNow(2),
    applied_at: daysAgo(10),
    result_status: 'ongoing',
    notes: '笔试链接已发邮箱，2小时限时，4道编程题',
    jd_url: null,
    jd_snapshot: null,
    resume_version: '前端-通用版',
    contact_info: 'HR邮箱: hr@alibaba.com',
    reminder_dismissed_at: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
  },

  // ========== 面试中 ==========
  {
    id: 'demo-006',
    user_id: GUEST_USER_ID,
    company_name: '快手',
    job_title: '前端开发实习',
    stage: '面试中',
    next_deadline: daysFromNow(1),
    applied_at: daysAgo(14),
    result_status: 'ongoing',
    notes: '一面通过，等二面通知\n一面问了：React Hooks 原理、性能优化、项目难点',
    jd_url: null,
    jd_snapshot: null,
    resume_version: '前端-项目版',
    contact_info: 'HR: 李女士 138xxxx1234',
    reminder_dismissed_at: null,
    created_at: daysAgo(14),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-007',
    user_id: GUEST_USER_ID,
    company_name: '网易',
    job_title: '游戏客户端开发',
    stage: '面试中',
    next_deadline: daysFromNow(0), // 今天
    applied_at: daysAgo(20),
    result_status: 'ongoing',
    notes: '今天下午3点 HR 面',
    jd_url: null,
    jd_snapshot: 'Unity/C++ 开发，参与网易旗舰游戏开发',
    resume_version: '游戏-客户端版',
    contact_info: '腾讯会议号: 123-456-789',
    reminder_dismissed_at: null,
    created_at: daysAgo(20),
    updated_at: daysAgo(0),
  },

  // ========== Offer ==========
  {
    id: 'demo-008',
    user_id: GUEST_USER_ID,
    company_name: 'PDD',
    job_title: '后端开发工程师',
    stage: 'Offer',
    next_deadline: daysFromNow(7),
    applied_at: daysAgo(30),
    result_status: 'success',
    notes: 'Offer 已发！月薪 25k，需要在一周内答复',
    jd_url: null,
    jd_snapshot: null,
    resume_version: '后端-Java版',
    contact_info: 'HR: 王先生',
    reminder_dismissed_at: null,
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
  },

  // ========== 已结束 ==========
  {
    id: 'demo-009',
    user_id: GUEST_USER_ID,
    company_name: '百度',
    job_title: '前端开发工程师',
    stage: '已结束',
    next_deadline: null,
    applied_at: daysAgo(25),
    result_status: 'failed',
    notes: '二面挂了，反馈是项目深度不够',
    jd_url: null,
    jd_snapshot: null,
    resume_version: '前端-通用版',
    contact_info: null,
    reminder_dismissed_at: null,
    created_at: daysAgo(25),
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-010',
    user_id: GUEST_USER_ID,
    company_name: 'B站',
    job_title: '前端开发实习',
    stage: '已结束',
    next_deadline: null,
    applied_at: daysAgo(40),
    result_status: 'withdrawn',
    notes: '拿到 PDD offer 后主动放弃',
    jd_url: null,
    jd_snapshot: null,
    resume_version: '前端-通用版',
    contact_info: null,
    reminder_dismissed_at: null,
    created_at: daysAgo(40),
    updated_at: daysAgo(5),
  },
]
